name: Security

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: Run zizmor
        run: pipx run zizmor .
